version: 2.1

orbs:
  python: circleci/python@1.5.0
  #docker:

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run flake8
          command: flake8
  build-docker:
    environment:
      IMAGE_NAME: oc-lettings
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker build -t "$CIRCLE_SHA1" .
            docker tag "$CIRCLE_SHA1" "$DOCKER_USERNAME"/oc_lettings:"$CIRCLE_SHA1"
            docker push "$DOCKER_USERNAME"/oc_lettings:"$CIRCLE_SHA1"
  heroku-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build app and send Docker IMG to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a oc-lettings-thomas web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release --app oc-lettings-thomas web

workflows:
  sample:
    jobs:
      - build-and-test
      - build-docker:
          requires:
            - build-and-test
      - heroku-deploy:
          requires:
            - build-and-test
            - build-docker
